l_korean:
 PRODUCTION_OPERATIONAL_FACTORIES_LABEL:0 "민간인 공장들"
 PRODUCTION_CONSUMER_GOODS:0 "소비자 좋은"
 PRODUCTION_CONSUMER_GOODS_LABEL:0 "§H소비자 좋은§!"
 PRODUCTION_CIVILIAN_FACTORIES_OWNED:0 "소유하는: $VAL|H$"